paper = lande_roi_monte_carlo_simulation_wg_june_27_2012

all: 
	pdflatex $(paper)

clean:
	rm -f $(paper).aux $(paper).log $(paper).out \
		$(paper).toc $(paper).bbl \
		$(paper).blg $(paper).nav $(paper).snm
